checks:
  php:
    code_rating: true
    duplication: true
    excluded_dependencies:
      - magento/framework

filter:
    excluded_paths:
        - "Test/"

build:
    dependencies:
        before:
            - 'echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json'
